# Generated by Django 4.0.4 on 2022-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="score",
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
