# Generated by Django 4.0.4 on 2022-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_run_score_submission_score_delete_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="competition",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="published at"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
