# Generated by Django 4.0.4 on 2022-05-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_phase_alter_competition_pub_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="competition",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="competitions.competition",
            ),
            preserve_default=False,
        ),
    ]
