# Generated by Django 4.0.4 on 2022-05-16 15:38

import django.core.files.storage
from django.db import migrations, models

import mlcompete.competitions.models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_phase_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="data_file",
            field=models.FileField(
                blank=True,
                help_text="file containing the features",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/Marius.Helf/Documents/mlcompete/uploads"
                ),
                upload_to=mlcompete.competitions.models.data_file_path,
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="labels_file",
            field=models.FileField(
                blank=True,
                help_text="file containing the labels",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/Marius.Helf/Documents/mlcompete/uploads"
                ),
                upload_to=mlcompete.competitions.models.labels_file_path,
            ),
        ),
    ]
