# Generated by Django 4.0.4 on 2022-05-17 13:21

import django.core.files.storage
from django.db import migrations, models

import mlcompete.competitions.models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0006_phase_data_file_name_phase_labels_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="custom label for this submission",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="script_file",
            field=models.FileField(
                default=0,
                help_text="file containing the submission script",
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/Marius.Helf/Documents/mlcompete/uploads"
                ),
                upload_to=mlcompete.competitions.models.submission_file_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="script_file_name",
            field=models.CharField(default="none", max_length=256),
            preserve_default=False,
        ),
    ]
